spring:
  application:
    name: votacion-backend
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  datasource:
    primary:
      url: jdbc:postgresql://votos-db:5432/votacion_votos
      username: admin
      password: admin123
    secondary:
      url: jdbc:postgresql://info-db:5432/votacion_info
      username: admin
      password: admin123

server:
  port: 8080
  address: 0.0.0.0

logging:
  level:
    com.votacion: INFO
