spring:
  application:
    name: votacion-backend
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    primary:
      url: jdbc:postgresql://localhost:5432/votacion_votos
      username: admin
      password: admin123
      driver-class-name: org.postgresql.Driver
    secondary:
      url: jdbc:postgresql://localhost:5433/votacion_info
      username: admin
      password: admin123
      driver-class-name: org.postgresql.Driver

server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-message: always

logging:
  level:
    com.votacion: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO
